### ISSUE TITLE
Bug: Date range filter is not working

### ISSUE THREAD

**Issue by melon-ruet** [CraftsmenLtd/empalIssues#11]
As an Cempal "employee" user
Given I have access to cempal 
When I try to filter my leaves by date
Then I can see it's not filtering by "Start Date" or "End Date"
And maybe it's filtering leaves by "Application Date" or "Approval Date"

While tried to check my C/L at May with from date April 1 to June 16, I can see it's not appeared
<img width="1316" alt="Screenshot 2023-05-17 at 11 43 26 AM" src="https://github.com/CraftsmenLtd/empalIssues/assets/4718893/b834a929-617d-4c63-9cd7-bd7ea1f48a89">

But when I try to check that with March 1 to June 16, I can see it
<img width="1319" alt="Screenshot 2023-05-17 at 11 58 34 AM" src="https://github.com/CraftsmenLtd/empalIssues/assets/4718893/53b01b64-30d8-44e5-a3d4-eccd1d4eba52">

I think the range is relatd with "Application Date" or "Approval date"

Related Url: https://staging.cempal.craftsmenltd.com/employee
Environment: staging

**Comment by raiyan-hosn** [comment]
Thanks @melon-ruet for raising this issue.
Yes you are right! This filter is applied on the "Application Submission Date" not on the "Start Date" or "End Date". Later on we have realized that this filter should be applied on "Start Date" and "End Date" for better user experience.
You can check this now. Any leave application which is fully or partially matches with the date range should appear in the search result.
