### ISSUE TITLE
Why are we exposing AWS information through the URL?

### ISSUE THREAD

**Issue by XAbirHasan** [CraftsmenLtd/empalIssues#4]
In general, it is not considered good practice to expose the underlying implementation details of your API, such as the hostname or domain name of your backend server. Doing so could potentially reveal sensitive information to external parties and make it easier for attackers to target your infrastructure.

Instead, it is recommended to use a domain name that is separate from your backend infrastructure, and to set up appropriate security measures such as firewalls and access control policies to restrict access to your backend servers.

If you must expose your backend hostname or IP address, it is recommended to use encryption and authentication measures to help protect your infrastructure from unauthorized access.

## Screenshots
<img src="https://user-images.githubusercontent.com/67853959/228450635-1913455d-25cb-4d2e-a652-c4eb8af84484.png" width="700">

**Comment by raiyan-hosn** [comment]
Thank you @XAbirHasan for raising this issue. 
We have fixed it accordingly. May you please have a look again?

**Comment by XAbirHasan** [comment]
fix looks good.
